import { useState } from 'react';
import type { DocData } from '../model/types';
import { Breadcrumb } from './Breadcrumb';
import { Icon } from './Icon';
import { RichText } from './RichText';
import { SymbolSection } from './SymbolSection';

export { TableOfContents } from './TableOfContents';

interface DocViewerProps {
  data: DocData;
  layout: 'linear' | 'split';
}

export const DocViewer = ({ data, layout }: DocViewerProps) => {
  const [isDepsExpanded, setIsDepsExpanded] = useState(false);
  const importsCount = data.imports?.length || 0;
  const VISIBLE_IMPORTS = 8;
  const visibleImports = isDepsExpanded ? data.imports : data.imports.slice(0, VISIBLE_IMPORTS);

  function handleDefinitionClick(startLine: number) {
    console.log('[DocViewer] Navigate to line:', startLine);
  }

  function handleDependenciesClick() {
    setIsDepsExpanded(!isDepsExpanded);
  }

  return (
    <div className={`mx-auto ${layout === 'split' ? 'px-16 py-12' : ''}`}>
      <Breadcrumb path={data.meta.path} filename={data.meta.filename} />

      <header className="mb-24 mt-8">
        <h1 className="text-4xl md:text-5xl font-serif font-bold text-gray-900 mb-8 tracking-tight leading-snug">
          {data.meta.filename}
        </h1>

        <div className="max-w-3xl font-serif text-base md:text-lg text-gray-600 leading-relaxed pl-6 border-l-4 border-gray-900 py-2 mb-10">
          <RichText content={data.meta.description || 'No description provided.'} />
        </div>

        <div className="flex flex-wrap gap-x-12 gap-y-6 font-sans text-xs text-gray-500 uppercase tracking-widest border-t border-gray-100 pt-6">
          <div>
            <span className="block text-2xs text-gray-400 mb-1">Author</span>
            <span className="text-gray-900 font-bold">{data.meta.author || 'Unknown'}</span>
          </div>
          <div>
            <span className="block text-2xs text-gray-400 mb-1">Version</span>
            <span className="text-gray-900 font-bold">{data.meta.version || '1.0.0'}</span>
          </div>
          <div>
            <span className="block text-2xs text-gray-400 mb-1">Last Modified</span>
            <span className="text-gray-900 font-bold">{data.meta.lastModified || new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </header>

      {data.imports && data.imports.length > 0 && (
        <section className="mb-24">
          <h3 className="font-sans text-xs font-bold uppercase tracking-widest text-gray-900 mb-4 flex items-center gap-2">
            <Icon name="package" className="w-3 h-3 text-gray-400" />
            Dependencies <span className="text-gray-300 font-light">|</span>{' '}
            <span className="text-gray-400 font-normal">{importsCount} modules</span>
          </h3>

          <div className="flex flex-wrap gap-2 items-center">
            {visibleImports.map((imp, i) => (
              <div
                key={i}
                title={imp.path}
                className="inline-flex items-center gap-2 px-3 py-1.5 bg-gray-50 border border-gray-200 rounded-lg hover:bg-white hover:border-gray-300 hover:shadow-sm transition-all cursor-pointer group"
              >
                <Icon name="package" className="w-3 h-3 text-gray-400 group-hover:text-blue-500 transition-colors" />
                <span className="font-mono text-xs font-bold text-gray-700 group-hover:text-gray-900 transition-colors">
                  {imp.name}
                </span>
              </div>
            ))}

            {importsCount > VISIBLE_IMPORTS && (
              <button
                onClick={handleDependenciesClick}
                className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-bold text-gray-500 hover:text-gray-900 transition-colors"
              >
                {isDepsExpanded ? (
                  <>
                    Show Less <Icon name="arrowUp" className="w-3 h-3" />
                  </>
                ) : (
                  <>
                    +{importsCount - VISIBLE_IMPORTS} more <Icon name="arrowDown" className="w-3 h-3" />
                  </>
                )}
              </button>
            )}
          </div>
        </section>
      )}

      <div className="mb-32">
        {data.symbols?.map((symbol, idx) => (
          <SymbolSection key={idx} symbol={symbol} layout={layout} onDefinitionClick={handleDefinitionClick} />
        ))}
      </div>

      <footer className="pt-12 border-t border-gray-100 flex justify-between items-center text-gray-400">
        <div className="font-serif text-sm">Generated by TSDoc GenAI</div>
        <div className="font-sans text-2xs tracking-widest uppercase">{new Date().toLocaleDateString()}</div>
      </footer>
    </div>
  );
};
